# Generated by Django 2.2.16 on 2022-09-02 16:17

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[reviews.models.year_validator], verbose_name='Год издания'),
        ),
    ]
